# This workflow sets up Snyk scans

name: Snyk Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule: # Run snyk scan daily at midnight
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  snyk-python:
    permissions:
      contents: read       # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read        # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Python 3.12 environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Install Snyk CLI into the Python 3.12 environment
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Snyk Python report vulnerabilities
      - name: Snyk Python report vulnerabilities
        run: snyk test --sarif-file-output=snyk.sarif --policy-path=.snyk --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: snyk.sarif
